# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "Virtual Site Setup Extension"
version = "0.1.0"  # Semantic Versionning is used: https://semver.org/
description = "A setup extension for a USD Composer based template application."
category = "Setup"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "extension", "setup"]  # Search keywords for the Extension Manager
preview_image = "data/preview.png"  # Preview to show in the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI
repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"  # URL of the extension source repository


[dependencies]
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.kit.property.usd" = {}
"omni.kit.quicklayout" = {}
"omni.kit.stage_templates" = {}
"omni.kit.viewport.menubar.lighting" = { optional = true }
"omni.kit.window.property" = {}
"omni.kit.window.title" = {}
"omni.ui" = {}
"omni.usd" = {}


[settings.app.menu]
legacy_mode = false


[settings.exts."omni.kit.viewport.menubar.lighting"]
rigs = "${ff.virtual_site_setup_extension}/data/light_rigs"
defaultRig = "Default"


[[python.module]]
name = "ff.virtual_site_setup_extension"


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
    "omni.kit.mainwindow",
    "omni.kit.ui_test",
]

args = [
    "--/app/fastShutdown=1",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/height=720",
    "--/app/window/scaleToMonitor=false",
    "--/app/window/width=1280",
    "--/exts/omni.kit.viewport.window/startup/windowName=Viewport",
    "--no-window",
    "--reset-user"
]
